apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    deployment: swy-go-builder
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: /
  name: swy-go-builder
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: swy-go-builder
  template:
    metadata:
      labels:
        deployment: swy-go-builder
        swybuild: golang
      name: swy-go-builder
    spec:
      containers:
      - name: golang-build
        image: "swiftycloudou/golang"
        imagePullPolicy: Always
        env:
        - name: SWD_INSTANCE
          value: "build"
        - name: SWD_PORT
          value: "8687"
        - name: SWD_LANG
          value: "golang"
        - name: SWD_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        volumeMounts:
        - mountPath: /go/src/swycode
          name: code
      volumes:
      - hostPath:
          path: /home/swifty-volume
        name: code
