- name: Add Kubernetes yum repository
  yum_repository:
    name: Kubernetes
    description: Kubernetes Repository
    file: kubernetes
    baseurl: http://yum.kubernetes.io/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgcheck: no
- name: Install kubernetes packages (RHEL/CentOS)
  dnf:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: latest

- name: Disable selinux
  shell: "setenforce 0"

- name: Disable system swap
  shell: "swapoff -a"

- name: Remove current swaps from fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '(?i)^([^#][\S]+\s+(none|swap)\s+swap.*)'
    line: '# \1'
    backrefs: yes
    state: present

- name: Disable swappiness
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { name: 'vm.swappiness', value: '0' }

- name: Enable and restart kubelet engine
  systemd:
    name: kubelet
    daemon_reload: yes
    state: started
    enabled: yes

- name: ensure net.bridge.bridge-nf-call-iptables is set to 1
  shell: |
    cat <<EOF >  /etc/sysctl.d/k8s.conf
    net.bridge.bridge-nf-call-ip6tables = 1
    net.bridge.bridge-nf-call-iptables = 1
    EOF
    sysctl --system

- name: Join to Kubernetes clusters
  tags: worker
  shell: |
    kubeadm join --skip-preflight-checks \
                 --token {{ token }} \
                 {{ hostvars[groups['swy-core'][0]]['core_private_ip'] }}:6443 \
                 --discovery-token-unsafe-skip-ca-verification

- name: Enable and restart kubelet engine
  systemd:
    name: kubelet
    daemon_reload: yes
    state: started
    enabled: yes
