- name: copy swifty.config.json
  template:
    src: swifty.config.j2
    dest: /root/swifty.config.json
    owner: root
    group: root
    mode: 0644

- name: pull python image
  shell: docker pull swiftycloudou/python

- name: pull nodejs image
  shell: docker pull swiftycloudou/nodejs

- name: start ui
  shell: docker run -d -p 80:80 --name ui --restart always -v /root/swifty.config.json:/html/swifty.config.json:ro swiftycloudou/ui
