- name: install mariadb
  dnf:
    name:
      - mariadb-server
      - mariadb-server-utils
      - python3-devel
      - mysql-devel
      - gcc
    state: latest

- name: enable  mariadb service
  systemd:
    name: mariadb
    enabled: yes
    masked: no

- name: start mariadb service
  systemd: state=started name=mariadb

- name: Install the mysqlclient module
  pip:
    name: mysqlclient
    executable: pip3
