- name: Add Kubernetes yum repository
  yum_repository:
    name: Kubernetes
    description: Kubernetes Repository
    file: kubernetes
    baseurl: http://yum.kubernetes.io/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgcheck: no
- name: Install kubernetes packages (RHEL/CentOS)
  dnf:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: latest

- name: Disable selinux
  shell: "setenforce 0"

- name: Disable system swap
  shell: "swapoff -a"

- name: Remove current swaps from fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '(?i)^([^#][\S]+\s+(none|swap)\s+swap.*)'
    line: '# \1'
    backrefs: yes
    state: present

- name: Disable swappiness
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { name: 'vm.swappiness', value: '0' }

- name: Enable and restart kubelet engine
  systemd:
    name: kubelet
    daemon_reload: yes
    state: started
    enabled: yes

- name: ensure net.bridge.bridge-nf-call-iptables is set to 1
  shell: |
    cat <<EOF >  /etc/sysctl.d/k8s.conf
    net.bridge.bridge-nf-call-ip6tables = 1
    net.bridge.bridge-nf-call-iptables = 1
    EOF
    sysctl --system

- name: pull k8s images
  shell: kubeadm config images pull --kubernetes-version=v1.11.0

- name: Init Kubernetes cluster
  shell: |
    kubeadm init --pod-network-cidr {{ pod_network_cidr }} \
                 --kubernetes-version=v1.11.0 \
                 --token {{ token }}
  tags: master

- name: Create Kubernetes config directory
  file: path="~/.kube/" state=directory
  tags: master

- name: Change permissions of .kube/config
  file: path=/etc/kubernetes/admin.conf mode=0775
  tags: master

- name: Copy admin.conf to Home directory
  copy:
    src: "{{ kubeadmin_config }}"
    dest: "~/.kube/config"
    owner: root
    group: root
    mode: 0755
    remote_src: True
  tags: master

- name: create flannel network
  shell: "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.10.0/Documentation/kube-flannel.yml"
  tags: master
